/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: e2b0f06e2c9fe8733d20d4168d3c5bae)
interface __BaseEnv_CloudflareEnv {
	MEALS_DB: D1Database;
<<<<<<< HEAD
=======
	AI: Ai;
	IMAGES: ImagesBinding;
>>>>>>> 83b68ff (Improve meal variety and TikTok import with Workers AI.)
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
